### ISSUE TITLE
Fails to start. Illegal instruction

### ISSUE THREAD

**Issue by wengole** [timhaak/docker-transmission#1]
When running 
```
docker run -v /pool/Bittorrent/incoming:/watch -v /pool/Bittorrent/complete:/downloads -v /pool/Bittorrent/incomplete:/incomplete -v /pool/Bittorrent/config:/config -p 45555:45555 -p 9091:9091 -e "USERNAME=username" -e "PASSWORD=password" timhaak/transmission
```
I get
```
/start.sh: line 21:     8 Illegal instruction     (core dumped) /usr/local/bin/transmission-daemon --foreground --config-dir /config --log-info --username ${USERNAME} --peerport 45555 --password ${PASSWORD} --auth --watch-dir /watch --download-dir /downloads --incomplete-dir /incomplete
```

**Comment by timhaak** [comment]
Hi

Are you building it your self? Or are pulling the image.

If your puling the image have you pulled the latest version.

**Comment by timhaak** [comment]
Sorry ignore me I see your using timhaak/transmission.

Have done a 
 
    docker pull timhaak/transmission:latest 

recently?

I've just tested with the latest version on my side and it all works?

More trying to see how to replicate the problem.

**Comment by wengole** [comment]
Hi,

I tried pulling again and docker fetched something, however re-running the same start command again, resulted in the exact same error.

My guess is it's got nothing to do with the container configuration/setup but more to do with my host OS and the ports I'm trying to open. I will get back to you.

**Comment by timhaak** [comment]
Cool thanks.

What os are you on? Also which version of docker are you running ?

**Comment by wengole** [comment]
Hi,

Sorry I didn't get back to you. I gave up on this container :(

My OS is Manjaro (Arch) running Linux 3.19.4 and docker 1.5.0.

If you have any ideas, I'm willing to try it again.

**Comment by timhaak** [comment]
I've pushed  some update to the git repo.

Though will start properly testing tomorrow. Managed to break my internet so waiting for them to fix before start pulling images down to test.

**Comment by Rodeoclash** [comment]
@timhaak did those updates make it through to the docker hub? I pulled the latest version from there a few hours ago and I've also run into the Illegal instruction error.

Host machine is a 64 bit Ubuntu. Cpuinfo:

```
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips	: 4533.49
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

I had a successful install of this image about a week ago onto a Digital Ocean host.

**Comment by timhaak** [comment]
I did. 

I'm also running on ubuntu 14.04 though off a real server.

I'll try find some time this weekend to spin up a server on digital ocean and test.

Just confirming that your using 14.04

**Comment by timhaak** [comment]
Please try now found a place that I can replicate and think it should be fixed.

Also some strangeness when I build locally it works but when its built on the index it doesn't with some of the old stuff.

But think it should be sorted everywhere.

**Comment by timhaak** [comment]
Going to close as working on the system that was broken.

If you still have problems shout and will re-open

**Comment by wengole** [comment]
Yep, it works now. Thanks.
