### ISSUE TITLE
settings.json is a symlink

### ISSUE THREAD

**Issue by lrusak** [timhaak/docker-transmission#2]
The settings.json file is a symlink in the /config directory. This makes it impossible to edit on the host.

```
root@transmission:/# ls -lh /config
total 12K
drwxr-xr-x 2 root root 4.0K Oct 13 07:54 blocklists
drwxr-xr-x 2 root root 4.0K Oct 13 07:54 resume
lrwxrwxrwx 1 root root   38 Oct 13 08:16 settings.json -> /etc/transmission-daemon/settings.json
drwxr-xr-x 2 root root 4.0K Oct 13 07:54 torrents
```

**Comment by timhaak** [comment]
Hmm that's odd as looking at the scripts the link should be working the other way round.

Just checked mine and it appears all correct. 

Possibly this is from an older version and as your linking it in its still got the old symlink.

Try removing the file from the config directory and then doing a new pull and run.
