### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by mdreizin** [timhaak/docker-transmission#3]
```
[2016-01-23 09:02:23.830 UTC] transmission-daemon Error loading config file -- exiting. (daemon.c:519)
mv: failed to access ‘/config/settings.json’: Too many levels of symbolic links
```

**Comment by timhaak** [comment]
Hi the location that the config file is located are you doing symbolic link's there ?

It's working this side so more trying to find out what's different in your location?

**Comment by mdreizin** [comment]
Hello @timhaak, thanks for the response. I have started from scratch using:

```
docker run --restart=always -d --name transmission --net="host" -v ~/transmission:/config -v ~/media/watch:/watch -v ~/media/downloads:/downloads -v ~/media/incomplete:/incomplete -p 51413: 45555 -p 9091:9091 -e "USERNAME=username" -e "PASSWORD=password" timhaak/transmission
```

and `~/transmission` is empty.

If I copy `settings.json` into `~/transmission` then it works fine.

**Comment by timhaak** [comment]
Ok think it should be fixed now. They changed how they were storing the config. The one I was grabbing is now a symlink :). Now pointing to the non symlinked version.

**Comment by mdreizin** [comment]
@timhaak I was wrong it doesn't work now with the following cmd:

```
docker run --restart=always -d --name transmission -v ~/transmission:/config -v ~/media/watch:/watch -v ~/media/downloads:/downloads -v ~/media/incomplete:/incomplete -p 45555:45555 -p 9091:9091 -e "USERNAME=username" -e "PASSWORD=password" timhaak/transmission
```

I have got:

```
[2016-01-23 10:49:34.262 UTC] transmission-daemon Error loading config file -- exiting. (daemon.c:519)
mv: failed to access ‘/config/settings.json’: Too many levels of symbolic links
```

**Comment by mdreizin** [comment]
@timhaak I'm sorry It was my mistake.

I deleted `timhaak/transmission` image and ran `docker run --restart=always -d --name transmission -v ~/transmission:/config -v ~/media/watch:/watch -v ~/media/downloads:/downloads -v ~/media/incomplete:/incomplete -p 45555:45555 -p 9091:9091 -e "USERNAME=username" -e "PASSWORD=password" timhaak/transmission` and now it works fine.

**Comment by timhaak** [comment]
Possibly it pulled the new image? Or the new image hadn't finished building.

Glad it working now :)
